language: node_js
node_js: stable

sudo: required
# S: Build Lifecycle
install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - git config --global user.name 'chaozh'
  - git config --global user.email chao@hust.edu.cn
  # 替换同目录下的_config.yml文件中gh_token字符串,注意此处sed命令用了双引号,单引号无效
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy

cache:
  apt: true
  directories:
    - node_modules

branches:
  only:
    - src